"""
summarize_all.py — assemble all reviewer-response tables from phase CSVs.

Reads:
  results/tables/main_results.csv          (paper seed=42 baseline)
  results/tables/phase1_multiseed.csv      (M1)
  results/tables/phase2_results.csv        (M3, M4)
  results/tables/phase3_results.csv        (M5, M6)
  results/tables/phase4_sensitivity.csv    (M7)
  results/tables/phase23_extra_bootstrap_ci.csv (M3/M5/M6 multi-seed check)
  results/tables/phase3_results_v2.csv     (M5 decontaminated rerun, 2026-07-11)
  results/tables/phase3_bootstrap_ci_v2.csv (M5 decontaminated bootstrap CI)

Emits:
  results/tables/reviewer_response_table.md  — one markdown table per M-item
"""
import os
import sys
import pandas as pd
import numpy as np

sys.stdout.reconfigure(encoding="utf-8")

TABLE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "results", "tables")
OUT = os.path.join(TABLE_DIR, "reviewer_response_table.md")


def load(fname):
    p = os.path.join(TABLE_DIR, fname)
    if not os.path.exists(p):
        return None
    df = pd.read_csv(p)
    if "alpha_mode" in df.columns:
        df["alpha_mode"] = df["alpha_mode"].fillna("N/A")
    return df


def pct(x):
    return f"{x*100:.2f}" if x == x else "n/a"


def row_from(df, sampler=None, loss=None, alpha=None, seed=42, tag=None):
    if df is None:
        return None
    q = pd.Series(True, index=df.index)
    if tag is not None:
        q &= (df.sampler == tag)
    else:
        if sampler is not None: q &= (df.sampler == sampler)
    if loss is not None:  q &= (df.loss == loss)
    if alpha is not None: q &= (df.alpha_mode == alpha)
    if seed is not None:  q &= (df.seed == seed)
    r = df[q]
    return None if len(r) == 0 else r.iloc[0]


def section(lines, title):
    lines.append("")
    lines.append(f"## {title}")
    lines.append("")


def main():
    main_df = load("main_results.csv")
    p1_df   = load("phase1_multiseed.csv")
    p2_df   = load("phase2_results.csv")
    p3_df   = load("phase3_results.csv")
    p3_contaminated = load("phase3_results_contaminated.csv")
    p3_v2   = load("phase3_results_v2.csv")
    p3_boot_v2 = load("phase3_bootstrap_ci_v2.csv")
    p4_df   = load("phase4_sensitivity.csv")
    p1_sum  = load("phase1_summary.csv")
    p1_boot = load("phase1_bootstrap_ci.csv")
    p23_boot = load("phase23_extra_bootstrap_ci.csv")
    p5_multiseed = load("phase5_nonefl_multiseed.csv")
    p5_boot = load("phase5_bootstrap_ci.csv")
    p6_multiseed = load("phase6_cbhas_flfixed_multiseed.csv")
    p6_boot = load("phase6_bootstrap_ci.csv")

    def boot_row_p5(desc):
        if p5_boot is None:
            return None
        r = p5_boot[p5_boot.comparison == desc]
        return None if len(r) == 0 else r.iloc[0]

    def boot_row(desc):
        if p23_boot is None:
            return None
        r = p23_boot[p23_boot.comparison == desc]
        return None if len(r) == 0 else r.iloc[0]

    def boot_row_v2(desc):
        if p3_boot_v2 is None:
            return None
        r = p3_boot_v2[p3_boot_v2.comparison == desc]
        return None if len(r) == 0 else r.iloc[0]

    lines = ["# Reviewer-response assembled tables", "",
             "Generated by `src/summarize_all.py`.  Each section maps one reviewer",
             "comment to concrete numbers from the phase CSVs."]

    # ── M1: multi-seed ────────────────────────────────────────────────────────
    section(lines, "M1 — Multi-seed statistics (Phase 1)")
    if p1_sum is not None:
        lines.append("| Config | Mean F1 | Std | Seeds |")
        lines.append("|--------|---------|-----|-------|")
        for _, r in p1_sum.iterrows():
            lines.append(f"| {r.config} | {r.mean_f1:.2f} | {r.std_f1 if r.std_f1==r.std_f1 else 'n/a'} | {r.n_seeds} |")
    else:
        lines.append("_Phase 1 not yet run.  Command:  `bash src/run_phase1.sh`_")
    if p1_boot is not None:
        lines.append("")
        lines.append("**Paired bootstrap 95 % CI on Macro-F1 differences:**")
        lines.append("")
        lines.append("| Comparison | Δ (pp) | 95 % CI | p | Significant |")
        lines.append("|------------|--------|---------|---|-------------|")
        for _, r in p1_boot.iterrows():
            sig = "yes" if r["significant_at_0.05"] else "no"
            lines.append(f"| {r.comparison} | {r.mean_delta:+.2f} | "
                         f"[{r.CI95_lo:+.2f}, {r.CI95_hi:+.2f}] | {r.p_value:.4f} | {sig} |")

    # ── M2: fact-check (uses main_results only) ───────────────────────────────
    section(lines, "M2 — Abstract number correction")
    r_none  = row_from(main_df, sampler="none",   loss="ce")
    r_ros   = row_from(main_df, sampler="ros",    loss="ce")
    r_smote = row_from(main_df, sampler="smote",  loss="ce")
    r_ada   = row_from(main_df, sampler="adasyn", loss="ce")
    r_ctgan = row_from(main_df, sampler="ctgan",  loss="ce")
    r_tvae  = row_from(main_df, sampler="tvae",   loss="ce")

    if r_tvae is not None:
        f = r_tvae.macro_f1 * 100
        lines.append(f"CB-HAS+CE Macro-F1 = **{f:.2f} %**.")
        lines.append("")
        lines.append("| Baseline | F1 | Δ vs CB-HAS |")
        lines.append("|----------|-----|------------|")
        for name, r in [("none+CE", r_none), ("ROS+CE", r_ros), ("SMOTE+CE", r_smote),
                        ("ADASYN+CE", r_ada), ("CTGAN+CE", r_ctgan)]:
            if r is not None:
                lines.append(f"| {name} | {r.macro_f1*100:.2f} | {f - r.macro_f1*100:+.2f} pp |")
        lines.append("")
        lines.append("**Recommendation**: Replace abstract's *'20.53 points over the best "
                     "traditional oversampling method'* with either")
        lines.append(f"*'{f - r_ros.macro_f1*100:.2f} pp over the best oversampling baseline (ROS)'*"
                     " or")
        lines.append(f"*'{f - r_ctgan.macro_f1*100:.2f} pp over the strongest data-level baseline (CTGAN)'*.")

    # ── M3: routing ablation ─────────────────────────────────────────────────
    section(lines, "M3 — Cardinality routing ablation")
    if p2_df is not None:
        r_tvae_all   = row_from(p2_df, tag="tvae_all",   loss="ce")
        r_interp_all = row_from(p2_df, tag="interp_all", loss="ce")
        rows = []
        if r_tvae is not None:      rows.append(("CB-HAS (default routing)", r_tvae))
        if r_tvae_all is not None:  rows.append(("TVAE-all (force TVAE, no fallback)", r_tvae_all))
        if r_interp_all is not None:rows.append(("Interp-all (force SMOTE for every rare class)", r_interp_all))
        if rows:
            lines.append("| Variant | Macro-F1 |")
            lines.append("|---------|----------|")
            for name, r in rows:
                lines.append(f"| {name} | {r.macro_f1*100:.2f} |")
            if r_tvae is not None and r_tvae_all is not None:
                lines.append(f"\nDelta CB-HAS vs TVAE-all: **{(r_tvae.macro_f1 - r_tvae_all.macro_f1)*100:+.2f} pp** "
                             "(supports M3: routing is necessary for extremely rare classes).")
            if r_tvae is not None and r_interp_all is not None:
                lines.append(f"Delta CB-HAS vs Interp-all: **{(r_tvae.macro_f1 - r_interp_all.macro_f1)*100:+.2f} pp** "
                             "(supports M3: TVAE is necessary for medium-cardinality classes).")
        b1, b2 = boot_row("CB-HAS vs TVAE-all (M3)"), boot_row("CB-HAS vs Interp-all (M3)")
        if b1 is not None or b2 is not None:
            lines.append("")
            lines.append(f"**Multi-seed check (seeds {b1.seeds if b1 is not None else b2.seeds}, "
                         "paired bootstrap 95 % CI on Δ vs CB-HAS):**")
            lines.append("")
            lines.append("| Comparison | Δ (pp) | 95 % CI | p | Significant |")
            lines.append("|------------|--------|---------|---|-------------|")
            for b in (b1, b2):
                if b is not None:
                    sig = "yes" if b["significant_at_0.05"] else "no"
                    lines.append(f"| {b.comparison} | {b.mean_delta:+.2f} | "
                                 f"[{b.CI95_lo:+.2f}, {b.CI95_hi:+.2f}] | {b.p_value:.4f} | {sig} |")
            lines.append("")
            lines.append("**Caveat**: the single-seed (42) deltas above do *not* hold up across seeds — "
                         "both comparisons cross zero once seeds 123/2024 are included (one seed each "
                         "reverses the sign). The routing-necessity claim is **not** statistically "
                         "supported with n=3 seeds; treat M3 as a design/efficiency choice rather than "
                         "a proven accuracy gain.")

    # ── M4: none + FL ────────────────────────────────────────────────────────
    section(lines, "M4 — none + Focal Loss control")
    if p2_df is not None:
        r_none_fl_sqrt  = row_from(p2_df, sampler="none", loss="focal", alpha="sqrt_inverse")
        r_none_fl_fixed = row_from(p2_df, sampler="none", loss="focal", alpha="fixed")
        rows = []
        if r_none is not None:        rows.append(("none + CE",              r_none))
        if r_none_fl_sqrt is not None:  rows.append(("none + FL (sqrt_inv)",   r_none_fl_sqrt))
        if r_none_fl_fixed is not None: rows.append(("none + FL (α=0.25)",     r_none_fl_fixed))
        if rows:
            lines.append("Seed-42 reference point:")
            lines.append("")
            lines.append("| Config | Macro-F1 |")
            lines.append("|--------|----------|")
            for name, r in rows:
                lines.append(f"| {name} | {r.macro_f1*100:.2f} |")

    if p5_multiseed is not None:
        lines.append("")
        lines.append("**Multi-seed extension (2026-07-11, seeds 7/42/123/1337/2024): none+FL(fixed) and "
                     "none+FL(sqrt_inverse) each retrained on 4 new seeds; sampler=none never reaches the "
                     "resample() CAP/downsample code path, self-checked (BENIGN=1,257,033 preserved) in "
                     "every run.**")
        lines.append("")
        lines.append("| Config | Mean F1 | Std | Seeds |")
        lines.append("|--------|---------|-----|-------|")
        none_ce_row = p1_sum[p1_sum.tag == "A"].iloc[0] if p1_sum is not None else None
        if none_ce_row is not None:
            lines.append(f"| none+CE | {none_ce_row.mean_f1:.2f} | {none_ce_row.std_f1} | {none_ce_row.n_seeds} |")
        for alpha, label in [("fixed", "none+FL(α=0.25)"), ("sqrt_inverse", "none+FL(sqrt_inv)")]:
            vals = p5_multiseed[p5_multiseed.alpha_mode == alpha].macro_f1.values * 100
            if len(vals):
                lines.append(f"| {label} | {vals.mean():.2f} | {vals.std(ddof=1):.3f} | {len(vals)} |")
        b_fixed = boot_row_p5("none+FL(fixed) vs none+CE")
        b_sqrt  = boot_row_p5("none+FL(sqrt_inv) vs none+CE")
        if b_fixed is not None or b_sqrt is not None:
            lines.append("")
            lines.append("**Paired bootstrap 95 % CI on Macro-F1 differences (Δ = FL − CE):**")
            lines.append("")
            lines.append("| Comparison | Δ (pp) | 95 % CI | p | Significant |")
            lines.append("|------------|--------|---------|---|-------------|")
            for b in (b_fixed, b_sqrt):
                if b is not None:
                    sig = "yes" if b["significant_at_0.05"] else "no"
                    lines.append(f"| {b.comparison} | {b.mean_delta:+.2f} | "
                                 f"[{b.CI95_lo:+.2f}, {b.CI95_hi:+.2f}] | {b.p_value:.4f} | {sig} |")
            lines.append("")
            lines.append("**Not the same story for both weighting schemes.** Fixed-α (0.25) Focal Loss is "
                         "statistically indistinguishable from CE even with no augmentation at all (Δ=+1.57 "
                         "pp, CI crosses zero). But sqrt-inverse Focal Loss is *already* significantly worse "
                         "than CE on the un-augmented data (Δ=-7.42 pp, CI [-12.42,-2.69], p<0.001) — see "
                         "below for what this means once CB-HAS+FL(fixed) is also multi-seeded.")

    if p6_multiseed is not None and p6_boot is not None:
        lines.append("")
        lines.append("**CB-HAS+FL(fixed) multi-seed completion (2026-07-11, seeds 7/42/123/1337/2024): "
                     "reused the exact same cached per-seed TVAE-augmented training sets as CB-HAS+CE "
                     "(phase1_multiseed.csv) — verified byte-for-byte identical class distribution to the "
                     "original Phase-1 generation logs (BENIGN=1,257,033, all 7 routed classes==5,000) "
                     "before reuse — so this is a clean same-seed, same-augmented-set paired comparison "
                     "differing only in loss function.**")
        lines.append("")
        vals = p6_multiseed.macro_f1.values * 100
        lines.append(f"CB-HAS+FL(fixed): mean={vals.mean():.2f}, std={vals.std(ddof=1):.3f}, n={len(vals)}")
        lines.append("")
        b = p6_boot.iloc[0]
        sig = "yes" if b["significant_at_0.05"] else "no"
        lines.append("| Comparison | Δ (pp) | 95 % CI | p | Significant |")
        lines.append("|------------|--------|---------|---|-------------|")
        lines.append(f"| {b.comparison} | {b.mean_delta:+.2f} | [{b.CI95_lo:+.2f}, {b.CI95_hi:+.2f}] | "
                     f"{b.p_value:.4f} | {sig} |")
        lines.append("")
        lines.append("**This reverses the single-seed impression.** At seed=42 alone, CB-HAS+FL(fixed) "
                     "looked 6.26 pp worse than CB-HAS+CE (Section 4.4, Finding 3) — but across 5 seeds "
                     "the gap is -0.26 pp with a CI comfortably straddling zero (p=0.75): CB-HAS+CE and "
                     "CB-HAS+FL(fixed) are statistically indistinguishable. Combined with the none-arm "
                     "result above, the complete 2×2 picture is: fixed-α Focal Loss is statistically neutral "
                     "relative to CE both with and without augmentation (no augmentation-interaction effect "
                     "survives multi-seed testing), while sqrt-inverse Focal Loss is significantly worse "
                     "than CE both with and without augmentation (Δ=-7.42 pp no-aug, Δ=-9.10 pp with CB-HAS "
                     "aug) — i.e. sqrt-inverse weighting looks like a generally weak scheme, not evidence of "
                     "an augmentation × loss over-correction interaction. **The paper's Finding 3 "
                     "('Focal Loss over-corrects after sufficient augmentation') does not survive multi-seed "
                     "testing in the form stated for either weighting scheme, and needs to be retracted or "
                     "substantially rewritten.**")

    # ── M5: matched-budget baselines ─────────────────────────────────────────
    section(lines, "M5 — Sampling-budget fairness (matched)")
    lines.append("**SUPERSEDED (2026-07-11): the original M5 result below was contaminated and is "
                 "retracted.** `resample()`'s memory-safety cap silently downsampled BENIGN and three "
                 "other classes to 50,000 samples each (from 1,257,033 / 103,708 / 76,808 / 54,416) "
                 "before ROS/SMOTE/ADASYN ran — a step CB-HAS never undergoes. This was never a "
                 "budget-matching mechanism; it deleted ~87% of the majority-class training data for "
                 "these three baselines only. Fixed in `train.py` (`resample()` now skips the cap "
                 "entirely on the matched-budget path, with a runtime self-check asserting every "
                 "non-augmented class is byte-for-byte preserved). All 9 configs (3 samplers × seeds "
                 "42/123/2024) were rerun clean. **The corrected result reverses the original "
                 "conclusion**: see 'Decontaminated result' below.")
    if p3_df is not None:
        rows = []
        for tag in ["ros_matched", "smote_matched", "adasyn_matched"]:
            r = row_from(p3_df, tag=tag, loss="ce")
            if r is not None:
                rows.append((tag, r))
        # Paper defaults for comparison
        if r_ros is not None:    rows.insert(0, ("ros (default, from paper)",    r_ros))
        if r_smote is not None:  rows.insert(1, ("smote (default, from paper)",  r_smote))
        if r_ada is not None:    rows.insert(2, ("adasyn (default, from paper)", r_ada))
        if rows:
            lines.append("")
            lines.append("**Contaminated result (retracted, kept for the record):**")
            lines.append("")
            lines.append("| Config | Macro-F1 | Macro-Precision |")
            lines.append("|--------|----------|-----------------|")
            for name, r in rows:
                lines.append(f"| {name} | {r.macro_f1*100:.2f} | {r.macro_precision*100:.2f} |")
        bros, bsmote, bada = (boot_row("CB-HAS vs ROS matched (M5)"),
                               boot_row("CB-HAS vs SMOTE matched (M5)"),
                               boot_row("CB-HAS vs ADASYN matched (M5)"))
        if any(b is not None for b in (bros, bsmote, bada)):
            seeds_str = next(b.seeds for b in (bros, bsmote, bada) if b is not None)
            lines.append("")
            lines.append(f"Contaminated multi-seed check (seeds {seeds_str}, paired bootstrap 95 % CI on Δ vs CB-HAS):")
            lines.append("")
            lines.append("| Comparison | Δ (pp) | 95 % CI | p | Significant |")
            lines.append("|------------|--------|---------|---|-------------|")
            for b in (bros, bsmote, bada):
                if b is not None:
                    sig = "yes" if b["significant_at_0.05"] else "no"
                    lines.append(f"| {b.comparison} | {b.mean_delta:+.2f} | "
                                 f"[{b.CI95_lo:+.2f}, {b.CI95_hi:+.2f}] | {b.p_value:.4f} | {sig} |")

    if p3_v2 is not None:
        lines.append("")
        lines.append("**Decontaminated result (authoritative, 2026-07-11):**")
        lines.append("")
        lines.append("| Config | Seed | Macro-F1 | Macro-Precision |")
        lines.append("|--------|------|----------|-----------------|")
        for tag in ["ros_matched", "smote_matched", "adasyn_matched"]:
            for seed in [42, 123, 2024]:
                r = row_from(p3_v2, tag=tag, loss="ce", seed=seed)
                if r is not None:
                    lines.append(f"| {tag} | {seed} | {r.macro_f1*100:.2f} | {r.macro_precision*100:.2f} |")
        bros2, bsmote2, bada2 = (boot_row_v2("CB-HAS vs ros_matched (decontaminated)"),
                                  boot_row_v2("CB-HAS vs smote_matched (decontaminated)"),
                                  boot_row_v2("CB-HAS vs adasyn_matched (decontaminated)"))
        if any(b is not None for b in (bros2, bsmote2, bada2)):
            lines.append("")
            lines.append("**Decontaminated multi-seed check (seeds 42,123,2024, paired bootstrap 95 % CI on Δ vs CB-HAS):**")
            lines.append("")
            lines.append("| Comparison | Δ (pp) | 95 % CI | p | Significant |")
            lines.append("|------------|--------|---------|---|-------------|")
            for b in (bros2, bsmote2, bada2):
                if b is not None:
                    sig = "yes" if b["significant_at_0.05"] else "no"
                    lines.append(f"| {b.comparison} | {b.mean_delta:+.2f} | "
                                 f"[{b.CI95_lo:+.2f}, {b.CI95_hi:+.2f}] | {b.p_value:.4f} | {sig} |")
            lines.append("")
            lines.append("**This no longer holds up.** Once the majority class is no longer silently "
                         "downsampled, CB-HAS and matched-budget ROS/SMOTE/ADASYN are statistically "
                         "indistinguishable (all three Δ are within ±1.1 pp of zero, all CIs cross "
                         "zero, all p > 0.5). SMOTE_matched even outperforms CB-HAS at seed 2024 "
                         "(82.33 vs 77.47). Combined with M1/M3/M6, **no baseline in this paper shows "
                         "a statistically significant Macro-F1 deficit against CB-HAS at n = 3-5 seeds** "
                         "except CB-HAS+CE vs CB-HAS+FL(√inv) (M1/M4). The paper's central quantitative "
                         "claim needs to be reframed around this finding, not around traditional-"
                         "oversampling superiority.")

    # ── M6: strict CTGAN ──────────────────────────────────────────────────────
    section(lines, "M6 — Strict CTGAN (no FORCE_SMOTE)")
    if p3_df is not None:
        r_strict = row_from(p3_df, tag="ctgan_strict", loss="ce")
        rows = []
        if r_ctgan is not None:  rows.append(("CTGAN (paper, with FORCE_SMOTE on Bot/XSS)", r_ctgan))
        if r_strict is not None: rows.append(("CTGAN strict (no FORCE_SMOTE)", r_strict))
        if r_tvae is not None:   rows.append(("CB-HAS (TVAE + SMOTE fallback)", r_tvae))
        if rows:
            lines.append("| Config | Macro-F1 |")
            lines.append("|--------|----------|")
            for name, r in rows:
                lines.append(f"| {name} | {r.macro_f1*100:.2f} |")
        b_strict = boot_row("CB-HAS vs CTGAN strict (M6)")
        if b_strict is not None:
            lines.append("")
            lines.append(f"**Multi-seed check (seeds {b_strict.seeds}, paired bootstrap 95 % CI):**")
            lines.append("")
            lines.append("| Comparison | Δ (pp) | 95 % CI | p | Significant |")
            lines.append("|------------|--------|---------|---|-------------|")
            sig = "yes" if b_strict["significant_at_0.05"] else "no"
            lines.append(f"| {b_strict.comparison} | {b_strict.mean_delta:+.2f} | "
                         f"[{b_strict.CI95_lo:+.2f}, {b_strict.CI95_hi:+.2f}] | {b_strict.p_value:.4f} | {sig} |")
            lines.append("")
            lines.append("**Not significant** — consistent with M1: CB-HAS and CTGAN (with or without "
                         "FORCE_SMOTE) are statistically indistinguishable once seed variance is accounted for.")

    # ── M7: threshold sensitivity ─────────────────────────────────────────────
    section(lines, "M7 — Threshold sensitivity (τ_s × N_target)")
    if p4_df is not None:
        lines.append("| τ_s | N_target | Macro-F1 |")
        lines.append("|-----|----------|----------|")
        # Origin from main_results
        if r_tvae is not None:
            lines.append(f"| 50 | 5000 | **{r_tvae.macro_f1*100:.2f}** (origin from paper) |")
        for _, r in p4_df.iterrows():
            # parse tag e.g. tvae_taus20_N5000
            tag = r.sampler
            parts = tag.split("_")
            try:
                ts = [p for p in parts if p.startswith("taus")][0][4:]
                nt = [p for p in parts if p.startswith("N")][0][1:]
                lines.append(f"| {ts} | {nt} | {r.macro_f1*100:.2f} |")
            except Exception:
                lines.append(f"| ?  | ?    | {r.macro_f1*100:.2f} (tag={tag}) |")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {OUT}")
    print(f"\nPreview:\n{'-'*60}")
    for ln in lines[:60]:
        print(ln)


if __name__ == "__main__":
    main()
